name: Deploy Nuxt to GitHub Pages

on:
  push:
    branches: [ main ]          # каждый push в main = новый деплой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Кэш npm или yarn (ускоряет сборку)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'          # или 'yarn'

      - run: npm ci             # или yarn install
      - run: npm run generate   # создаёт dist/
      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
